config/routes.rb
Rails.application.routes.draw do
  root to: 'books#index'
  resources :books, only:[:index, :new, :create]
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/book.rb
class Book < ApplicationRecord
  validates :title, presence: true
  validates :author, presence: true
  validates :date, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def new
    @book = Book.new
  end

  def create
    @book = Book.new(book_params)
    if @book.save
      redirect_to root_path
    else
      render :new
    end
  end

  private
  def book_params
    params.require(:book).permit(:title, :author, :date, :memo)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/views/books/_form.html.erb
<%= form_with(model: book, local: true) do |form| %>
  <%= render 'layouts/error_messages', model: form.object %>
  <%= form.text_field :title, placeholder: "タイトル" %>
  <%= form.text_field :author, placeholder: "著者" %>
  <%= form.text_field :date, placeholder: "読了日" %>
  <%= form.text_area :memo, placeholder: "メモ" %>
  <%= form.submit "SEND" %>
<% end %>

app/views/books/index.html.erb
<h1>読書履歴TOP</h1>

<div class="new">
  <%= link_to '本を登録する', new_book_path %>
</div>

<div class="all-book">
  <% @books.each do |book| %>
    <%= book.title %>
  <% end %>
</div>

app/views/books/new.html.erb
<h2>本の登録</h2>

<%= render partial: 'form', locals: {book: @book} %>

app/views/layouts/_error_messages.html.erb
<% if model.errors.any? %>
  <div class="error-alert">
    <ul>
      <% model.errors.full_messages.each do |message| %>
        <li class='error-message'><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Welbok</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>